package com.maithmuzic.common.db.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Sessions")
public class ActiveSession extends Session {
    @Override
    @DynamoDBHashKey(attributeName = "SecurityToken")
    public String getSecurityToken() {
        return securityToken;
    }

    @Override
    @DynamoDBAttribute(attributeName = "SessionId")
    @DynamoDBAutoGeneratedKey
    public String getSessionId() {
        return sessionId;
    }

    @Override
    @DynamoDBAttribute(attributeName = "Username")
    public String getUsername() {
        return username;
    }
}
