package com.maithmuzic.common.db.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "Albums")
public class Album {
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "Language")
    @DynamoDBTypeConverted(converter = Language.LanguageConverter.class)
    private Language language;

    @DynamoDBAttribute(attributeName = "Genres")
    @DynamoDBTypeConverted(converter = Genre.GenresListConverter.class)
    private List<Genre> genres;

    // alpha2Code of the country
    @DynamoDBAttribute(attributeName = "Country")
    private String country;

    // list of songs' id
    @DynamoDBAttribute(attributeName = "Songs")
    private List<String> songs;

    @DynamoDBAttribute(attributeName = "Musicians")
    private List<String> musicians;

    @DynamoDBAttribute(attributeName = "Singers")
    private List<String> singers;

    @DynamoDBAttribute(attributeName = "Lyricists")
    private List<String> lyricists;

    @DynamoDBAttribute(attributeName = "Tags")
    private List<String> tags;

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public Language getLanguage() {
        return language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public List<Genre> getGenres() {
        return genres;
    }

    public void setGenres(List<Genre> genres) {
        this.genres = genres;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public List<String> getSongs() {
        return songs;
    }

    public void setSongs(List<String> songs) {
        this.songs = songs;
    }

    public List<String> getMusicians() {
        return musicians;
    }

    public void setMusicians(List<String> musicians) {
        this.musicians = musicians;
    }

    public List<String> getSingers() {
        return singers;
    }

    public void setSingers(List<String> singers) {
        this.singers = singers;
    }

    public List<String> getLyricists() {
        return lyricists;
    }

    public void setLyricists(List<String> lyricists) {
        this.lyricists = lyricists;
    }

    @Override
    public String toString() {
        return "Album{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", language=" + language +
                ", genres=" + genres +
                ", country='" + country + '\'' +
                ", songs=" + songs +
                ", musicians=" + musicians +
                ", singers=" + singers +
                ", lyricists=" + lyricists +
                ", tags=" + tags +
                '}';
    }
}
