package com.maithmuzic.common.db.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "Albums")
public class Album {
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "Language")
    private Language language;

    // alpha2Code of the country
    @DynamoDBAttribute(attributeName = "Country")
    private String country;

    // list of songs' id
    @DynamoDBAttribute(attributeName = "Songs")
    private List<String> songs;

    @DynamoDBAttribute(attributeName = "Musicians")
    private List<String> musicians;

    @DynamoDBAttribute(attributeName = "Singers")
    private List<String> singers;

    @DynamoDBAttribute(attributeName = "Lyricists")
    private List<String> lyricists;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public List<String> getSongs() {
        return songs;
    }

    public void setSongs(List<String> songs) {
        this.songs = songs;
    }

    public List<String> getMusicians() {
        return musicians;
    }

    public void setMusicians(List<String> musicians) {
        this.musicians = musicians;
    }

    public List<String> getSingers() {
        return singers;
    }

    public void setSingers(List<String> singers) {
        this.singers = singers;
    }

    public List<String> getLyricists() {
        return lyricists;
    }

    public void setLyricists(List<String> lyricists) {
        this.lyricists = lyricists;
    }
}
