package com.maithmuzic.common.db.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBDocument
public abstract class Artist {
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    protected String id;

    @DynamoDBAttribute(attributeName = "Name")
    protected String name;

    @DynamoDBAttribute(attributeName = "Country")
    protected String country;

    @DynamoDBAttribute(attributeName = "Languages")
    @DynamoDBTypeConverted(converter = Language.LanguagesListConverter.class)
    protected List<Language> languages;

    @DynamoDBAttribute(attributeName = "Genres")
    @DynamoDBTypeConverted(converter = Genre.GenresListConverter.class)
    protected List<Genre> genres;

    @DynamoDBAttribute(attributeName = "Tags")
    protected List<String> tags;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public List<Language> getLanguages() {
        return languages;
    }

    public void setLanguages(List<Language> languages) {
        this.languages = languages;
    }

    public List<Genre> getGenres() {
        return genres;
    }

    public void setGenres(List<Genre> genres) {
        this.genres = genres;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }
}
