package com.maithmuzic.common.db.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;

@DynamoDBTable(tableName = "Songs")
public class Song {
    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "Title")
    private String title;

    @DynamoDBRangeKey(attributeName = "AlbumId")
    private String albumId;

    @DynamoDBAttribute(attributeName = "Language")
    @DynamoDBTypeConverted(converter = Language.LanguageConverter.class)
    private Language language;

    // list of singers' id
    @DynamoDBAttribute(attributeName = "Singers")
    private List<String> singers;

    @DynamoDBAttribute(attributeName = "Musicians")
    private List<String> musicians;

    @DynamoDBAttribute(attributeName = "Lyricist")
    private String lyricist;

    @DynamoDBAttribute(attributeName = "Genres")
    @DynamoDBTypeConverted(converter = Genre.GenresListConverter.class)
    private List<Genre> genres;

    @DynamoDBAttribute(attributeName = "Tags")
    private List<String> tags;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAlbumId() {
        return albumId;
    }

    public void setAlbumId(String albumId) {
        this.albumId = albumId;
    }

    public List<String> getSingers() {
        return singers;
    }

    public void setSingers(List<String> singers) {
        this.singers = singers;
    }

    public List<String> getMusicians() {
        return musicians;
    }

    public void setMusicians(List<String> musicians) {
        this.musicians = musicians;
    }

    public String getLyricist() {
        return lyricist;
    }

    public void setLyricist(String lyricist) {
        this.lyricist = lyricist;
    }

    public List<Genre> getGeners() {
        return genres;
    }

    public void setGeners(List<Genre> genres) {
        this.genres = genres;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public Language getLanguage() {
        return language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

    public List<Genre> getGenres() {
        return genres;
    }

    public void setGenres(List<Genre> genres) {
        this.genres = genres;
    }

    @Override
    public String toString() {
        return "Song{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", albumId='" + albumId + '\'' +
                ", language=" + language +
                ", singers=" + singers +
                ", musicians=" + musicians +
                ", lyricist='" + lyricist + '\'' +
                ", genres=" + genres +
                ", tags=" + tags +
                '}';
    }
}
